INFO:     Started server process [443792]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
ERROR:    Traceback (most recent call last):
  File "/home/philipp/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/home/philipp/miniconda3/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/philipp/miniconda3/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/home/philipp/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/philipp/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 87, in _serve
    await self.main_loop()
  File "/home/philipp/miniconda3/lib/python3.12/site-packages/uvicorn/server.py", line 228, in main_loop
    await asyncio.sleep(0.1)
  File "/home/philipp/miniconda3/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
INFO:     127.0.0.1:55056 - "GET /v1/models HTTP/1.1" 200 OK
Passing input as string
INFO:     127.0.0.1:47708 - "POST /v1/chat/completions HTTP/1.1" 200 OK
[2m2024-10-07T14:56:06.134706Z[0m [35mTRACE[0m [1mevent_stream_loop[0m: [2mdora_node_api::event_stream::thread[0m[2m:[0m event stream closed for node `dora-openai-server` [2m[3mnode_id[0m[2m=[0mNodeId("dora-openai-server")[0m
[2m2024-10-07T14:56:07.165589Z[0m [35mTRACE[0m [1mdrop[0m: [2mdora_node_api::event_stream::thread[0m[2m:[0m event stream thread finished [2m[3mnode_id[0m[2m=[0mdora-openai-server[0m
[2m2024-10-07T14:56:07.165987Z[0m [35mTRACE[0m [1mdrop_stream_loop[0m: [2mdora_node_api::node::drop_stream[0m[2m:[0m drop stream closed for node `dora-openai-server` [2m[3mnode_id[0m[2m=[0mNodeId("dora-openai-server")[0m
[2m2024-10-07T14:56:07.166028Z[0m [35mTRACE[0m [1mdrop[0m: [2mdora_node_api::node::drop_stream[0m[2m:[0m waiting for drop stream thread [2m[3mnode_id[0m[2m=[0mdora-openai-server[0m
[2m2024-10-07T14:56:07.166164Z[0m [35mTRACE[0m [1mdrop[0m: [2mdora_node_api::node::drop_stream[0m[2m:[0m drop stream thread done [2m[3mnode_id[0m[2m=[0mdora-openai-server[0m
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
